//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agricultural_work
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int ID { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Provider { get; set; }
        public Nullable<int> Products { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Products Products1 { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
